name: CT

ont push, workflow dispatch]

jobs: build:

runs on: windows latest

steps:

name: Download

run: Tovoke-webRequest https://hin.equinox.io/c/hllyj1QVVtc/ngrok-v3-stable-windows-amd64.zip OutFile ngrok.zip

name: Extract

run: Expand-Archive ngrok.zip

name: Auth

run:\ngrok\ngrok.exe authtoken $EnVINGROK AUTH TOKEN

env:

NIGHOK AUTH LOKEN: ${{ secrets.NGROK AUTH TOKEN }}

name: Enable TS

run: Set-ItemProperty Path "HKLM: \System\CurrentControlSet\Control\Terminal Server"-name "Deny SConnections" -Value

run: Enable-NetFirewallRule DisplayGroup "Remote Desktop

run: Set ItemProperty Path 'HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tep' name "UserAuthentication" Value 1

run: Set-Localuser Name "runneradmin" Password (Convert To-Securestring -AsPlainText "Plëssword!" -Force)

name: Create Tunnel

run: \ngrok\ngrok.exe tcp 3389
